apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 20150 # change this port with the given port range of your VCluster
    targetPort: 8080

